#!/bin/bash
#
# noip-updater
# ============
#
# Custom update script for No-IP
#
# Version: 2.0.0
# Author: Axel Rindle <mail@axelrindle.de>
# Documentation: https://github.com/axelrindle/noip-update-script
#

set -eu

# Build paths
DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
ENV_FILE=$DIR/.env

if [ -f "$ENV_FILE" ]; then
	# shellcheck source=.env
    source "$ENV_FILE"
fi

IPV4=$(curl --silent ifconfig.me)
IPV6=$(curl --silent ifconfig.co)
AUTH=$(echo "$USERNAME:$PASSWORD" | base64)
AGENT="$(uname -srom) $USERNAME [Script at https://github.com/axelrindle/noip-update-script]"

curl --silent \
	--header "Authorization: Basic $AUTH" \
	--header "User-Agent: $AGENT" \
	"https://dynupdate.no-ip.com/nic/update?hostname=$HOSTNAME&myip=$IPV4&myipv6=$IPV6"
